//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkotronicSystem.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MilkotronicSystemEntities : DbContext
    {
        public MilkotronicSystemEntities()
            : base("name=MilkotronicSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PCB_Data> PCB_Data { get; set; }
        public DbSet<PCB> PCBs { get; set; }
        public DbSet<Sensor> Sensors { get; set; }
        public DbSet<Thermo_Data> Thermo_Data { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
