//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkotronicSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCB
    {
        public PCB()
        {
            this.PCB_Data = new HashSet<PCB_Data>();
            this.Sensors = new HashSet<Sensor>();
            this.Thermo_Data = new HashSet<Thermo_Data>();
        }
    
        public int id { get; set; }
        public int pcbNumber { get; set; }
    
        public virtual ICollection<PCB_Data> PCB_Data { get; set; }
        public virtual ICollection<Sensor> Sensors { get; set; }
        public virtual ICollection<Thermo_Data> Thermo_Data { get; set; }
    }
}
