//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkotronicSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PCB_Data
    {
        public int id { get; set; }
        public int pcbId { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string operation { get; set; }
        public string model { get; set; }
        public Nullable<int> boxNumber { get; set; }
        public string speed { get; set; }
        public string Cal1 { get; set; }
        public string Cal2 { get; set; }
        public string Cal3 { get; set; }
        public string program { get; set; }
        public string data { get; set; }
        public string orderNumber { get; set; }
        public string ClientName { get; set; }
        public string country { get; set; }
        public string @operator { get; set; }
        public Nullable<double> programVersion { get; set; }
        public string options { get; set; }
        public int numberPcb { get; set; }
        public int numberSensor { get; set; }
    
        public virtual PCB PCB { get; set; }
    }
}
