//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkotronicSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensor
    {
        public int id { get; set; }
        public int number { get; set; }
        public int pcbId { get; set; }
    
        public virtual PCB PCB { get; set; }
    }
}
