//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilkotronicSystem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thermo_Data
    {
        public int id { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public Nullable<int> box { get; set; }
        public int pcbId { get; set; }
        public int sensor { get; set; }
        public Nullable<int> N40 { get; set; }
        public Nullable<int> P60 { get; set; }
        public string workplace { get; set; }
        public Nullable<double> programVersion { get; set; }
        public Nullable<int> ad623 { get; set; }
        public Nullable<int> amplitude { get; set; }
        public int numberPcb { get; set; }
    
        public virtual PCB PCB { get; set; }
    }
}
